Cleaned up :file:`conf.py` file.
